### ISSUE TITLE
Feature: Support for API key

### ISSUE THREAD

**Issue by hans00** [TheGrandWazoo/freenas-proxmox#112]
- Add API Key field
- If API key is defined, connect with api key
    - Change basic auth to `Authorization: Bearer ${API_KEY}`

**Comment by TheGrandWazoo** [comment]
Bump stale bot.

**Comment by TheGrandWazoo** [comment]
Currently looking into this and see how to implement it as an option. Username and password will still be needed due to Proxmox using iscsiadm over ssh to perform functions, but API calls should be able to use a Key.

Again, to use full API a total decouple and rewrite would be need on the plugin, which is not out of the question.

**Comment by TheGrandWazoo** [comment]
Bump so bot does not come alive.

**Comment by TheGrandWazoo** [comment]
Bump the bot.
