### ISSUE TITLE
Can't create targets in SCALE

### ISSUE THREAD

**Issue by mkomarinski** [TheGrandWazoo/freenas-proxmox#115]
If I try to move a disk to a new SCALE install using the same configuration that works for Core U12, I get:

create full clone of drive scsi0 (XXXXXXXXX:XXXXXXXXX)
Warning: volblocksize (4096) is less than the default minimum block size (8192).
To reduce wasted space a volblocksize of 16384 is recommended.
Use of uninitialized value $2 in sprintf at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 406.
Use of uninitialized value $product_name in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 407.
Use of uninitialized value $product_name in concatenation (.) or string at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 415.
Use of uninitialized value $product_name in string eq at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 515.
Use of uninitialized value $product_name in string eq at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 518.
iscsiadm: No session found.
drive mirror is starting for drive-scsi0
drive-scsi0: Cancelling block job
drive-scsi0: Done.
TASK ERROR: storage migration failed: mirroring error: VM 109 qmp command 'drive-mirror' failed - iSCSI: Failed to connect to LUN : Failed to log in to target. Status: Target not found(515) 

This happens with Proxmox 6.4 and 7.1.

**Comment by TheGrandWazoo** [comment]
Are you "moving" a disk from TrueNAS-Core to TrueNAS-Scale?

**Comment by mkomarinski** [comment]
No, from local disk to TrueNAS-Scale

**Comment by TheGrandWazoo** [comment]
I believe this to be fixed in the last commit.

If a path in Scale, for example 'tank/pve/disks', due to Scale using dashes (-) instead of slashes (/) the conversion would be 'tank-pve/disks' and then Scale would not find the extents.
The last commit fixed this. The only thing you may have to do on TrueNAS-Scale is manually change that slash to a dash.

I tested moving a local disk to TrueNAS-Scale and worked without issues.

**Comment by mkomarinski** [comment]
Confirmed.  I moved a disk as well and it looks like it's working. Thank you!

**Comment by TheGrandWazoo** [comment]
Excellent. Thanks for the support of the product.

**Comment by HB9HIL** [comment]
Seems like the issue reappeared. 

I can add the iSCSI Storage and with creating a VM it creates successfully a zvol in my TrueNAS Scale v 22.12.1

But if I try to start the VM it says 

`iscsiadm: No session found.
kvm: -drive file=iscsi://[MY-TRUENAS-IP]/iqn.2005-10.org.freenas.ctl:target0/0,if=none,id=drive-scsi0,format=raw,cache=none,aio=io_uring,detect-zeroes=on: iSCSI: Failed to connect to LUN : Failed to log in to target. Status: Target not found(515)
TASK ERROR: start failed: QEMU exited with code 1`

I don't really understand where I have to change slashes to dashes, because Scale is using dashes in the extent anyway. LUN ID 0 and Target are correct values in this case.
