### ISSUE TITLE
LUNs become inaccessible after migration to TrueNAS over iSCSI

### ISSUE THREAD

**Issue by surfrock66** [TheGrandWazoo/freenas-proxmox#167]
I'm using Proxmox 8.0.4 and TrueNAS Scale using the most up to date version of the plugin.  I have 2 hosts, and I think I've messed things up further than I can untangle, so the best I can do is describe where I'm at and how I got here.

Each of the hosts has a local ZFS storage pool, then I'm hoping to implement HA by having OS drives on the TrueNAS.  I started by making sure that I could take an existing VM's disk and do a storage move over to the TrueNAS; that was fine and is working well as it seems.  This works for both hosts; in the iscsi share config on TrueNAS, I can see both connected initiators, and it created an extent and a dataset for each VM (I initially tested with 5 VMs).  The issue then comes when I tried to migrate the VM's from one host to the other...the UI makes the migration appear successful, but it turns out the VM has hung and is completely inaccessible.  At that point I go to boot the VM, and Proxmox says no bootable device can be found.  This was the case for the 3 of the 5 VM's I migrated from host to host.  For now, all 3 of those VMs are stopped.

I tried to do a move of the storage back from the NAS to the local storage of these powered off VM's, but I cannot get the move to initiate at all, it shows the following in the console and then sits forever:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/6f05c9e3-69bd-4d8d-a519-b506b325eb15)

What's more concerning is the 2 remaining running VM's, they feel like time bombs where if I shut them down, they'll never boot again.  They appear to be running fine now.  I can't do the storage move back, I get the same thing as the screenshot above.

I'm stumped, and am not sure where else to look.  My 2 initiators are in an initiator group:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/8862b97d-da3d-4a5b-9661-c8ebadb90df3)

My extents were automatically created, I didn't make these:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/12b89426-a2d7-4d4d-93e8-107a8bf1f1a1)

The extents do not have a device selected, and the dropdown doesn't populate any devices:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/9bbbb676-20e5-46eb-b8b9-f2276257e060)

That being said, the devices are there, I can see them on the nas:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/5d8d2bc7-0460-4121-93e5-093f61242cb4)

The initiator group is associated with the target:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/3e45f09a-3083-4120-a3d5-b81cd182184a)

And lastly, the target is associated with the extents:

![image](https://github.com/TheGrandWazoo/freenas-proxmox/assets/1345467/1a9eba48-5a31-46cf-aa8d-abb07870b49f)

I'm way over my head, but any help is appreciated!

**Comment by surfrock66** [comment]
Minor update; the running VM's storage migrated back after like hours, which is good.

**Comment by surfrock66** [comment]
So after leaving it overnight, one of the offline VM's migrated its disk back to local storage on the proxmox host.  Upon trying to boot, no bootable device is found; I am worried the disk corrupted.

**Comment by isopix** [comment]
does it mean using freenas-proxmox is dangerous and shouldn't be used close to production?

**Comment by surfrock66** [comment]
I don't think so, I may be using this in the wrong way which is why I posted my configuration, I think with anything you should just be cautious and test first.

**Comment by eugenefvdm** [comment]
I've experimented a lot over the last few weeks. To keep my sanity I've stuck to every single default I can, so that if something goes wrong I know I did everything in the "standard way" and I can go back. The fact is there are many settings, e.g. "fine tuning", and who only knows what you're supposed to do. I'm not so much referring to the TrueNAS Core part, but rather to Proxmox VE.

In the last few weeks I've learnt:

- When migrating from the locally attached storage to iSCSI I get this warning:

```bash
create full clone of drive scsi0 (local-lvm:vm-102-disk-0)
Warning: volblocksize (4096) is less than the default minimum block size (8192).
To reduce wasted space a volblocksize of 8192 is recommended.
```

I made [a post](https://forum.proxmox.com/threads/whilst-move-storage-from-local-lvm-to-truenas-zfs-over-iscsi-warning-volblocksize-4096-is-less-than-the-default-minimum-block-size-8192.135053/#post-597080) on the Proxmox VE forum and although I got a quick reply I'm still confused. 

Is the TrueNAS ZFS default too big? Is Proxmox expecting something else? What are the implications of just matching the size? Can I change the size once I've already started creating VMs?

I also learnt:

- When you have a switch that perform no other operations, the performance is really good and consistent. The moment this switch is busy, the performance is a bit all over the show. I'm unfortunately limited to 1 GB switches.
- Bonding Ubiquiti switch ports from 1 GB to 2 GB made a difference in performance, but I still have inconsistent performance on these switches. I'm thinking I need something with a lot more powerful but 10 GB switches are quite pricey for the experimental phase since my hypervisor doesn't have 10 GB cards also. This seems to be a requirement if you like me want to run "10s" of VMs of iSCSI.
- VirtIO SCSI has a single mode. So the default was VirtIO SCSI "long ago" and then I installed a Proxmox Backup Server and it suddenly defaulted to VirtIO SCSI Single. I tried to understand the documentation but it's way over my head

Furthermore I'm still very confused about these Proxmox Hard Disk settings, but for the heck I've now mostly put them on:

- Discard. I think I understand this will discard free space, but why is the default off? Surely one always wants discard?
- IO thread. What's this about?
- SSD Emulation. Is this important?

Finally @surfrock66 you mention that extents are automatically created. I believe this is the whole point of this Proxmox plugin, is to help with those creation tasks. Stock Proxmox VE after all already has ZFS and all that jazz built-in, but you have a manual job when working with iSCSI. This plugin eliminates that manually work of extent creation. Why I think this is true is I connected the TrueNAS to a KVM installation where I had to do a lot this manual work, for example creating the extend.

To me the underlying network and components seems to be where one needs the power and stability. For example, I rebooted the NAS once with a few VMs "open" doing stuff, and most of them crashed. They didn't crash forever, but I certainly had to pamper them back to life. I'll only know once I have 10 GB switches in place but in my head iSCSI is iSCSI and the plugin is only a "wizard" for the most part.

**Comment by TheGrandWazoo** [comment]
As mentioned above, there is no `working portion` of the plugin during data transfers. It is basically a setup tool that gets information from the TrueNAS server to help Proxmox make all the connections. If you look at the iSCSI plugin, you must manually enter everything.
All the working parts are all in the underlying Proxmox iSCSI and ZFS modules along with the system iSCSI and ZFS drivers and apps. That is why we still need to use `username` and `password` to fetch the Volumes information from the server because Proxmox uses the `iscsiadm` tool to do that.

**Comment by TheGrandWazoo** [comment]
Also in your log file (syslog) if you don't see a `PVE::Storage::LunCmd::FreeNAS` on a line then the plugin is not being used at that time. See #170 for some examples.

**Comment by surfrock66** [comment]
Ok, I've been out of the country but it sounds like it might be after the initiation and more of a Proxmox/Iscsi issue, I'm gonna create a new VM and test (without live data).  I'll report back with findings.

**Comment by TheGrandWazoo** [comment]
Will be closing the first of the year if no additional information is posted.

**Comment by surfrock66** [comment]
Closing, this is likely not an issue with this initiator but with something closer to proxmox and truenas.
